source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
platform :ios, '8.0'
use_frameworks!

target "MissGe" do
    pod 'MJRefresh', '~> 3.1.15.1'
    pod 'Bugtags'
    
    pod 'TUNetworking'
    
    pod 'Alamofire', '~> 4.5.1'
    pod 'RxSwift', '~> 4.0.0'  #RxSwift的必备库
    pod 'RxCocoa', '~> 4.0.0'  #对 UIKit Foundation 进行 Rx 化
    pod 'RxDataSources', '~> 3.0.2'   # 帮助我们优雅的使用tableView的数据源方法
    pod 'Result', '~> 3.2.4'
    pod 'Differentiator', '~> 3.0.2'

    
    # 网络请求
    pod 'Moya/RxSwift'  # 为RxSwift专用提供，对Alamofire进行封装的一个网络请求库
    pod 'Moya', '~> 10.0.1'
    
    pod 'YYText', '~> 1.0.7'
    pod 'YYImage', '~> 1.0.4'
    pod 'YYCache', '~> 1.0.4'
    pod 'YYWebImage', '~> 1.0.5'
    
    pod 'SVProgressHUD', '~> 2.2.2'
    pod 'FXBlurView'
#    pod 'TZImagePickerController', '~> 1.9.6'
    pod 'TU_TZImagePickerController', :git => 'https://github.com/chengxianghe/TU_TZImagePickerController.git', :branch => 'YYImage_ImagePicker'
    pod 'XHPhotoBrowser', '~> 1.1.2'
#   pod 'SnapKit', '~> 4.0.0'

    pod 'KeychainAccess', '~> 3.1.0'
    
    pod 'ObjectMapper', '~> 3.1.0'
#    pod 'SwiftDate', '~> 4.0'

    #tabbar https://github.com/eggswift/ESTabBarController
    pod 'ESTabBarController-swift', '~> 2.5'
end
